### PR TITLE
[BUS-504]: notation for `createMocks` to enable tree-shaking

### PR DESCRIPTION
**Pull request by skellig-s**

### CODE REVIEW

**Comment by santam85** [comment]
Looks like BoatAngularTemplateTests needs updating

**Comment by skellig-s** [comment]
Tests are updated

**Review by cheshirsky — APPROVED** [review]

**Review by cheshirsky — COMMENTED** [review]
@skellig-s, we need to make sure we have it published with a correct version, so that we can use it right away, i.e. it should be `0.16.x`, not `0.17.x` version

**Comment by skellig-s** [comment]
Contribution rules have these two phrases:
> Make sure you update the release notes in the README.md file.
> Release notes for those are generated automatically from the merged PRs descriptions, and a new release draft is created at every release event.
Which one is correct? Should I manually update the release notes or is it done automatically?

**Comment by santam85** [comment]
The readme must be updated, the version that will be released is the one contained in the pom.xml (as a snapshot).
I'll correct the contribution guidelines.

**Comment by skellig-s** [comment]
Changelog updated

**Review by santam85 — APPROVED** [review]

**Pull request merged**
