### PR TITLE
Use ^ not >= in devDependencies of generated package.json files and…

### PR DESCRIPTION
**Pull request by daiscog**
…fix version of typescript used for Angular 11.

Also fix issues running `npm install` in the generated project when using npm v8.

### CODE REVIEW

**Review by brianvabb — APPROVED** [review]
So the problem was if the generated client was built with `ngVersion = angular@12`. BOAT was defining dev dependencies with range`>=` which would result in the latest versions being installed during `npm i`? (e.g, instead of `typescript@4.3.2` dev dependency being installed, it would install whatever the[ latest version was here](https://www.npmjs.com/package/typescript?activeTab=versions))

**Comment by daiscog** [comment]
> So the problem was if the generated client was built with `ngVersion = angular@12`. BOAT was defining dev dependencies with range`>=` which would result in the latest versions being installed during `npm i`? (e.g, instead of `typescript@4.3.2` dev dependency being installed, it would install whatever the[ latest version was here](https://www.npmjs.com/package/typescript?activeTab=versions))

Yeah, sorry, should have added a detailed explaination.

This affects people using BOAT to generate stand-alone clients for the specs, as opposed to people like us who generate the clients as libs within a bigger nx project (where the lib's devDependencies are ignored as we only install from the root package.json).

The problem is that [our instructions for generating custom clients with BOAT](https://community.backbase.com/documentation/foundation_angular/latest/create_data_module_using_open_api) say to do this to build the client package after generating it:

```
cd target/generated-sources/openapi
npm install
npm run build
```

Problem here is because of `>=` in the versions, `npm install` will install the _latest_ version of dev dependencies like `@angular/cli` and `ng-packagr` instead of the target major version the user intended.  This means the client is built using the Angular package format for the latest version of Angular which is not backwards compatible to older versions.  Then, when you try to use the lib in an app that uses the older version of Angular, you get an error like this:

```
.../fesm2015/xxx-http-ang.mjs: This application depends upon a library published using Angular version 14.2.9, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
```

**Comment by santam85** [comment]
LGTM, apart from a small conflict in the zone.js version used in tests it seems:
`[INFO] [INFO] Running 'npm install' in /home/runner/work/backbase-openapi-tools/backbase-openapi-tools/boat-maven-plugin/target/it/example/boat-generate/angular/target/http-module
[INFO] [INFO] npm ERR! code ERESOLVE
[INFO] [INFO] npm ERR! ERESOLVE unable to resolve dependency tree
[INFO] [INFO] npm ERR! 
[INFO] [INFO] npm ERR! While resolving: @boat/petstore-http-ang@2.2.0
[INFO] [INFO] npm ERR! Found: zone.js@0.11.8
[INFO] [INFO] npm ERR! node_modules/zone.js
[INFO] [INFO] npm ERR!   dev zone.js@"^0.11.4" from the root project
[INFO] [INFO] npm ERR! 
[INFO] [INFO] npm ERR! Could not resolve dependency:
[INFO] [INFO] npm ERR! peer zone.js@"~0.10.3" from @angular/core@10.2.5
[INFO] [INFO] npm ERR! node_modules/@angular/core
[INFO] [INFO] npm ERR!   dev @angular/core@"^10.0.0" from the root project
[INFO] [INFO] npm ERR!   peer @angular/core@"10.2.5" from @angular/common@10.2.5
[INFO] [INFO] npm ERR!   node_modules/@angular/common
[INFO] [INFO] npm ERR!     dev @angular/common@"^10.0.0" from the root project
[INFO] [INFO] npm ERR! 
[INFO] [INFO] npm ERR! Fix the upstream dependency conflict, or retry
[INFO] [INFO] npm ERR! this command with --force, or --legacy-peer-deps
[INFO] [INFO] npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[INFO] [INFO] npm ERR! 
[INFO] [INFO] npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.`

**Review by santam85 — APPROVED** [review]

**Comment by daiscog** [comment]
@santam85 yeah, just fixed those :)

**Pull request merged**
