### PR TITLE
WIP: Upgrade OpenAPI Generator 6.3.0 and support for Jakarta 

### PR DESCRIPTION
**Pull request by bartveenstra**

### CODE REVIEW

**Comment by santam85** [comment]
@bartv-bb will try changing the workflow to also push the snapshot versions on merge to main, so we can test this without releasing.

**Comment by santam85** [comment]
Can one of you confirm if the snaphshots versions are being correctly released? If so we can go ahead and test before even merging!

**Comment by bartveenstra** [comment]
Snapshot publsihed on https://oss.sonatype.org/content/repositories/snapshots/com/backbase/oss/

**Comment by miladbb** [comment]
[052078f](https://github.com/Backbase/backbase-openapi-tools/pull/437/commits/052078fe884a150e06c2c9f57d7605670db6c4a8) SpringBoot 2.x is now supported as well. The point is that the custom goals are only working with Spring3: 
- `generate-spring-boot-embedded`
- `generate-rest-template-embedded`
- `generate-webclient-embedded`

**Comment by miladbb** [comment]
3121c39ac53e6ce7397f05740334e1dce971972a : fix regarding this [issue](https://github.com/OpenAPITools/openapi-generator/pull/13550)  
By default `Set` is generated for arrays with `uniqueItems`. For generating `List` the following configurations are needed:
```
<typeMappings>set=List</typeMappings>
<instantiationTypes>set=ArrayList</instantiationTypes>
```

**Pull request merged**
